### ISSUE TITLE
Different values for Assembly Version and Assembly File Version

### ISSUE THREAD

**Issue by iappert** [appccelerate/Version#10]
Hi Appccelerators

I would like to have different values for the assembly version and the assembly file version and I'm planning to create a pull request. 

Would this feature be appreciated?
What would be your preferred way to implement this feature?
Possible solutions could be:
- using the tag annotations to specify the assembly file version format, e.g. adding something like assemblyFileVersion: 1.2.{0} to the annotation.
- using ms build settings, e.g.introducing formatting information as ms build settings
- extending the tag name, e.g. v=1.{0} afv:1.4.{0}
- introducing versioning configuration file, similar to git version

Feel free to suggest other ideas. By the way, great work.

Cheers Ivan

**Comment by ursenzler** [comment]
Hi Ivan

Currently, the whole annotation text is used as the `AssemblyInformationalVersion`. Therefore it is difficult to add the assembly file version to the annotation text. Especially in an backwards compatible way, without a lot of clutter/additional syntax.

I just don't like the idea of adding a configuration file :-)

I don't understand the idea with ms build setting.

Therefore I would go with something like this:

The tag looks like `v=1.{0} fv=1.4.{0}`. If we use v for assembly version, we should use fv for assembly file version, both with =.

In the method
```
public RepositoryVersionInformation GetRepositoryVersionInformation(Repository repository)
        {
            IEnumerable<Tag> allVersionTags = FindAllVersionTags(repository).ToArray();
            Commit lastTaggedCommit = FindLastVersionTaggedCommit(repository, allVersionTags);
            Tag latestVersionTag = FindLatestVersionTag(allVersionTags, lastTaggedCommit);
            int commits = CountCommitsSinceVersionTag(repository, lastTaggedCommit);
            string prereleaseOverride = DeterminePrereleaseOverride(repository);

--> parse assembly version and file version from latestVersionTag

            return new RepositoryVersionInformation(
--> use assembly version                ,
--> use file version, with fallback assembly version   ,
                commits,
                latestVersionTag.IsAnnotated ? latestVersionTag.Annotation.Message.Replace("\n", string.Empty).Replace("\r", string.Empty) : string.Empty,
                prereleaseOverride);
        }
```
I would look for the fv part and add this information to the `RepositoryVersionInformation`. If no file version is available, use the assembly version.

And finally, in 
```
private void WriteAssemblyInfoContaining(VersionInformation version)
        {
            string versionAssemblyInfo = string.Format(
                @"// <auto-generated> created by Appccelerate.VersionTask
using System;
using System.Reflection;

[assembly: AssemblyVersion(""{0}"")]
[assembly: AssemblyFileVersion(""{0}"")]
[assembly: AssemblyInformationalVersion(""{1}"")]
", 
```
write the file version instead of `{0}`.

Looking forward to the PR!

Happy coding
Urs

**Comment by ursenzler** [comment]
Solved with https://github.com/appccelerate/Version/pull/12
